export const defaultComments: Record<string, string> = {
  python: "# Start coding here",
  javascript: "// Start coding here",
  typescript: "// Start coding here",
  java: `// Start coding here`,
  cpp: "// Start coding here",
  c: "// Start coding here",
  go: "// Start coding here",
  php: "// Start coding here",
  ruby: "# Start coding here",
  swift: "// Start coding here",
  kotlin: "// Start coding here",
  rust: "// Start coding here",
  r: "# Start coding here",
  scala: "// Start coding here",
  perl: "# Start coding here",
  haskell: "-- Start coding here",
  lua: "-- Start coding here",
  dart: "// Start coding here",
};